name: Release develop

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: Updated version (if not set next minor is used)
        type: string
        required: false
        default: "Auto"

jobs:
  release:
    runs-on: judong
    timeout-minutes: 30
    env:
      SIGN_KEY_ID: ${{ secrets.GPG_KEYNAME }}
      SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
      SIGN_KEY: ${{ secrets.GPG_SECRET_KEYS }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      message: ${{ steps.success_message.outputs.message }}${{ steps.failure_message.outputs.message }}${{ steps.cancel_message.outputs.message }}

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ secrets.OSS_PAT }}
          fetch-depth: 2

      - name: ðŸ› ï¸ Project context
        id: context
        uses: zero88/gh-project-context@v1.2

      - name: ðŸ§¹ Remove toolchains.xml
        run: rm $HOME/.m2/toolchains.xml || true

      - name: ðŸ› ï¸ Set up JDK 17
        id : setupJava
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'


      - name: ðŸ§¹ Remove settings.xml
        run: rm $HOME/.m2/settings.xml || true

      - name: ðŸ› ï¸ Setup maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [
                {
                    "id": "judong-nexus-mirror",
                    "username": "${{ secrets.JUDONG_NEXUS_USERNAME }}",
                    "password": "${{ secrets.JUDONG_NEXUS_PASSWORD }}"
                },
                {
                    "id": "judong-nexus-distribution",
                    "username": "${{ secrets.JUDONG_NEXUS_USERNAME }}",
                    "password": "${{ secrets.JUDONG_NEXUS_PASSWORD }}"
                }
            ]
          mirrors: >
            [
                {
                    "id": "judong-nexus-mirror",
                    "mirrorOf": "*",
                    "url": "https://nexus.judo.technology/repository/maven-judong/"
                 }
            ]


      - name: â¬‡ï¸ Checkout master repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OSS_PAT }}
          ref: master
          fetch-depth: 0

      - name: ðŸ”ª Reset master branch to develop
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: ðŸ”¢ Calculate version number
        id: version
        run: |-
          TAG_NAME=$(echo "${{ steps.context.outputs.branch }}" | cut -d ' ' -f2 | tr '#\/\.-' '_')
          BASE_VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dtycho.mode=maven -DskipModules=true -Dexpression=project.version -q -DforceStdout | cut -d'-' -f 1)
          if [[ "${{ github.event.inputs.is_release }}" == "true" ]]; then
            VERSION_NUMBER=${BASE_VERSION}
          else
            VERSION_NUMBER=${BASE_VERSION}.$(date +%Y%m%d_%H%M%S)_${{ steps.context.outputs.shortCommitId }}_${TAG_NAME//[(\)]}
          fi
          echo "Base version from POM: $BASE_VERSION"
          echo "Building version: ${VERSION_NUMBER}"
          echo "version=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
          echo "base-version=${BASE_VERSION}" >> $GITHUB_OUTPUT

      - name: ðŸ”€ Merge master branch to release branch
        run: |
          git merge -s ours origin/master

      - name: Set release version
        run: |-
          ./mvnw versions:set-property -Dproperty=revision -DnewVersion=${{ steps.version.outputs.base-version }} -Dtycho.mode=maven -DskipModules=true

      - name: â¬†ï¸ Create Pull Request for release into master
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.OSS_PAT }}
          commit-message: '[RELEASE] Release version: ${{ steps.version.outputs.base-version }}'
          branch: release/v${{ steps.version.outputs.base-version }}
          delete-branch: true
          title: '[RELEASE] Release version: ${{ steps.version.outputs.base-version }} to master'
          body: >
            This PR is auto-generated. Creates pull request to master which contains the coresponding release's source code.
          labels: release, automated pr

      - name: â¬‡ï¸ Checkout develop repository
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: â­ï¸ Increase version number
        id: next_version
        run: |-
          NEXT_VERSION="${{ github.event.inputs.next_version }}"
          if [ -z "$NEXT_VERSION" ] || [ $NEXT_VERSION == "Auto" ]; then
            NEXT_VERSION=`(echo $(./mvnw build-helper:parse-version org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
              -Dtycho.mode=maven -DskipModules=true -Dexpression="parsedVersion.majorVersion" -q -DforceStdout) &&\
            echo "." && \
            echo $(./mvnw build-helper:parse-version org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
              -Dtycho.mode=maven -DskipModules=true -Dexpression="parsedVersion.minorVersion" -q -DforceStdout) &&\
            echo "." && \
            echo $(./mvnw build-helper:parse-version org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
              -Dtycho.mode=maven -DskipModules=true -Dexpression="parsedVersion.nextIncrementalVersion" -q -DforceStdout) &&\
            echo "-SNAPSHOT") \
            | tr -d '\n'`
          fi
          if [[ ! $NEXT_VERSION =~ ^.*-SNAPSHOT ]]; then
              NEXT_VERSION="${NEXT_VERSION}-SNAPSHOT"
          fi
          echo "Next version is: $NEXT_VERSION"
          echo "version=${NEXT_VERSION}" >> $GITHUB_OUTPUT

      - name: Set next version
        run: |-
          ./mvnw versions:set-property -Dproperty=revision -DnewVersion=${{ steps.next_version.outputs.version }} -Dtycho.mode=maven -DskipModules=true

      - name: â¬†ï¸ Create Pull Request for increased version into develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.OSS_PAT }}
          commit-message: '[RELEASE] Increase version to ${{ steps.next_version.outputs.version }}'
          branch: increment/v${{ steps.next_version.outputs.version }}
          delete-branch: true
          branch-suffix: short-commit-hash
          title: '[RELEASE] Set develop version to: ${{ steps.next_version.outputs.version }}'
          body: >
            This PR is auto-generated. Increasing development version and creates a pull request to develop.
          labels: release, automated pr

